site_name: Autogen
site_description: Automatic expression generator using Wickâ€™s theorem.
repo_url: https://github.com/asthanaa/autogen

docs_dir: docs
site_dir: site

theme:
  name: material

nav:
  - Home: index.md
  - Overview: overview.md
  - Installation: installation.md
  - Usage: usage.md
  - Concepts: concepts.md
  - API: api.md
  - Input/Output: io.md
  - Testing: testing.md
  - Performance: performance.md
  - Work log: work_log.md
